# Generated by Django 4.2.1 on 2023-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Превью')),
                ('file', models.FileField(upload_to='video/', verbose_name='Видео')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.DeleteModel(
            name='Downloader',
        ),
    ]
